### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by lukeck**
I keep wanting to run stackup from a Docker image so it would be helpful if it was officially packaged as one.

I've added a Dockerfile that uses the official Ruby 2.3 alpine image. It's larger than I expected at 130mb. The advertised size for the `ruby:2.3-alpine` image is 38mb but weighs in at 125mb on my system for some reason. I'm sure it could be slimmed down more with a bit of effort.

I've also been wanting a dev environment for this so I've added that too, along with `make` targets for test, build and release.

I've guessed at that the docker hub repository name matches the `realestate-com-au` github org name.

### CODE REVIEW

**Comment by mdub** [comment]
Thanks Luke.

Probably don't need both `$(TIMESTAMP)` and `$(VERSION)` when tagging the image.

I've have the "realestate" org on hub.docker.com for a while ... this might be an opportunity to use it.

**Comment by mdub** [comment]
As an alternative, we _could_ use an automated build on Docker Hub for this:

* https://docs.docker.com/docker-hub/builds/

**Comment by lukeck** [comment]
Can we merge this and move to automated Docker Hub builds later if setting them up now is proving to be problematic? I want to start using this.

**Comment by lukeck** [comment]
Closing because there's now an alternative implementation on master.

**Pull request closed without merging**
