### PR TITLE
Upgrade all the rubies - use 3.3 by default

### PR DESCRIPTION
**Pull request by tigris**

### CODE REVIEW

**Review by djmattyg007 — COMMENTED** [review]
I think this change makes a lot of sense 👍 Should we remove support for Ruby 2.7 while we're here?

**Comment by tigris** [comment]
> Should we remove support for Ruby 2.7 while we're here?

We could do that. Ruby 3.0 is also EOL as of 3 weeks ago, would you like that removed also?

**Comment by djmattyg007** [comment]
Yep, let's do it. It won't magically remove old versions that do claim support for it.

**Review by djmattyg007 — APPROVED** [review]
Thank you!

**Comment by rea-jonpad** [comment]
This also makes https://github.com/realestate-com-au/stackup/pull/101 redundant, and can be closed

**Comment by tigris** [comment]
Any chance we can get a release?

I do believe there is a `stackup-ci` pipeline you can just hit "new build" on 😺

**Pull request merged**
